"""test autogenerate

Revision ID: d300424c05cd
Revises: bb19f1772ac9
Create Date: 2023-11-06 11:38:19.995668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd300424c05cd'
down_revision: Union[str, None] = 'bb19f1772ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billboards', sa.Column('test_col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billboards', 'test_col')
    # ### end Alembic commands ###
